export const demoTrainers = [
  {
    id: "demo-1",
    name: "Dr. Ananya Rao",
    status: "APPROVED",
    skills: [
      "Doppler Radar",
      "Nowcasting",
      "Data Interpretation",
      "Severe Weather",
    ],
    relevant_years: 11,
    qualification_match: 0.95,
    performance: 0.96,
    availability: 0.9,
    certifications: 0.85,
    rating: 4.8,
  },
  {
    id: "demo-2",
    name: "Rajiv Menon",
    status: "APPROVED",
    skills: ["Doppler Radar", "Cyclone Forecasting", "Severe Weather"],
    relevant_years: 14,
    qualification_match: 0.9,
    performance: 0.94,
    availability: 0.8,
    certifications: 0.8,
    rating: 4.7,
  },
  {
    id: "demo-3",
    name: "Dr. Meera Iyer",
    status: "APPROVED",
    skills: ["Remote Sensing", "Satellite Interpretation"],
    relevant_years: 8,
    qualification_match: 0.95,
    performance: 0.92,
    availability: 0.5,
    certifications: 0.9,
    rating: 4.6,
  },
  {
    id: "demo-4",
    name: "Arjun Sen",
    status: "APPROVED",
    skills: ["Python", "Climate Data", "Data Interpretation"],
    relevant_years: 6,
    qualification_match: 0.8,
    performance: 0.9,
    availability: 1,
    certifications: 0.8,
    rating: 4.5,
  },
];
